[package]
name = "aoc_utils"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[features]
regex = ["dep:regex"]

[dependencies]
aoc_utils_proc_macro = { path = "proc_macro" }
regex = { version = "1.5.4", optional = true}
nom = "7.1.1"
itertools = "0.12.0"
paste = "1.0.15"
